#!/bin/bash
# scrpt show info about subdomains
get_record_info() {
  local domain=$1
  local subdomain=$2
  local record_type=$(dig +short $subdomain.$domain | awk '{print $4}')
  local destination=$(dig +short $subdomain.$domain | awk '{print $1}')
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
  get_record_info $domain www
  get_record_info $domain lb-01
  get_record_info $domain web-01
  get_record_info $domain web-02
else
  get_record_info $domain $subdomain
fi
