#!/usr/bin/env bash
# Script configure new Ubuntu machine to Perform 301-redirection

# Upadate pkgs before Installation
sudo apt-get update
sudo apt-get install -y nginx

# Creat index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Perform 301 Redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/abdelhamedatef2 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx service
sudo service nginx restart
