#!/usr/bin/env bash 
 # Script install Nginx server and redirects /redirect_me 
 apt-get -y update 
 apt-get -y install nginx 
 echo "Hello World!" > /var/www/html/index.nginx-index.html 
 sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/abdelhamedqtef2 permanent;/" /etc/nginx/sites-available/default 
 service nginx start 
 mv 
