#!/usr/bin/env bash
# script install and config HAProxy on lb-01 server
# Config HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Instal and config HAproxy on lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  mido_frontend
        bind *:80
        mode http
        default_backend mido_backend
backend mido_backend
        balance roundrobin
        server 230344-web-01 34.229.56.92:80 check
        server 230344-web-02 54.236.27.183:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testi HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart  Nginx service
sudo service haproxy restart
