#!/usr/bin/env bash
# script to install and configure HAProxy on lb-01 server
# Configure HAProxy and send traffic to web-01 , web-02 servers
# Distribute requests using roundrobin 
# confirm HAProxy can be managed by init script
# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install haproxy -y

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 34.229.56.92:80 check
    server web-02 54.236.27.183:80 check
EOT

# Test HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Start HAProxy
sudo systemctl start haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy
