#!/usr/bin/env bash
#script that displays "Best School" 10 times using for loop.

for i in {1..10}
do
  echo "Best School"
done#!/usr/bin/env bash
# This script displays "Best School" 10 times using a for loop.

for i in {1..10}
do
  echo "Best School"
done
