#!/usr/bin/env bash
#script uses while loop to display "Best School" ten times. On 9th iteration, it also displays "Hi".

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 8 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
