#!/usr/bin/env bash
# Fixe web server to run Nginx as user listen on port 8080

# set user in config by replace '#user' and it value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replace port 80 with 8080 in sites-available configuration
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# give owner permission to read, write to configration file
chmod 644 /etc/nginx/nginx.conf
# apache may interfere with nginx so kill process if it is run
pkill apache2
# start nginx service with new nginx user
sudo -u nginx service nginx start
